[tool.poetry]
name = 'python-creole'
version = '1.4.0'
description = ''
license = 'GPL-3.0-or-later'
authors = ['Jens Diemer <python-creole@jensdiemer.de>']
homepage = 'https://github.com/jedie/python-creole/'
keywords=['creole', 'markup', 'creole2html', 'html2creole', 'rest2html', 'html2rest', 'html2textile']
classifiers = [
    # http://pypi.python.org/pypi?%3Aaction=list_classifiers
    'Development Status :: 5 - Production/Stable',
    'Environment :: Web Environment',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: GNU General Public License (GPL)',
    'Programming Language :: Python',
    'Programming Language :: Python :: 2.7',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: Implementation :: PyPy',
    'Operating System :: OS Independent',
    'Topic :: Documentation',
    'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
    'Topic :: Software Development :: Libraries :: Python Modules',
    'Topic :: Text Processing :: Markup',
    'Topic :: Text Processing :: Markup :: HTML',
    'Topic :: Utilities',
]
packages = [
    { include = 'creole' },
]
include = ['README.creole']

[tool.poetry.dependencies]
python = '^3.6'
docutils = "^0.16"

[tool.poetry.dev-dependencies]
pytest = '^4.6'
pytest-cov = "^2.8.1"
isort = "^4.3.21"
black = "^19.10b0"
flake8 = "^3.7.9"
flynt = "^0.40.1"

[tool.poetry.scripts]
creole2html = 'creole.cmdline:cli_creole2html'
html2creole = 'creole.cmdline:cli_html2creole'
html2rest = 'creole.cmdline:cli_html2rest'
html2textile = 'creole.cmdline:cli_html2textile'

[build-system]
requires = ['poetry>=0.12']
build-backend = 'poetry.masonry.api'

